HranitelPROWeb/Controllers/AuthController.cs
using HranitelPROWeb.Data;
using HranitelPROWeb.Data.Entities;
using HranitelPROWeb.Models.Auth;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace HranitelPROWeb.Controllers
{
    public class AuthController : Controller
    {
        HranitelDBContext _dbContext;

        public AuthController(HranitelDBContext dbContext)
        {
            _dbContext = dbContext;
        }

        public async Task<IActionResult> Login(LoginViewModel model)
        {

            var user = await _dbContext.Polzovatelis.FirstOrDefaultAsync(u => u.Login == model.LoginUser
                && u.Parol == model.Password);

            if(user != null)
            {
                await AuthenticateAsync(user);
                return RedirectToAction("Index", "Home");
            }
            
            return View();
        }

        public async Task<IActionResult> Registration()
        {
            return View();
        }

        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }

        public async Task AuthenticateAsync(Polzovateli user)
        {
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.NameIdentifier, user.IdPolzovatelia.ToString()),
                new Claim(ClaimsIdentity.DefaultNameClaimType, user.Login)
            };

            var id = new ClaimsIdentity(claims, "ApplicationCookie", ClaimsIdentity.DefaultNameClaimType,
               ClaimsIdentity.DefaultRoleClaimType);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(id));
        }
    }
}

HranitelPROWeb/Controllers/RegApplicationController.cs
using HranitelPROWeb.Data;
using HranitelPROWeb.Data.Entities;
using HranitelPROWeb.Data.Repositories;
using HranitelPROWeb.Models.RegApplications;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HranitelPROWeb.Controllers
{
    public class RegApplicationController : Controller
    {
        private readonly HranitelDBContext _dbContext;

        private static GroupStepTwoViewModel regViewModel = new GroupStepTwoViewModel();
        private static GroupStepOneViewModel privacyViewModel = new GroupStepOneViewModel
        {
            Visitors = new List<Posetiteli>()
        };

        private static SoloViewModel soloViewModel = new SoloViewModel();

        public RegApplicationController(HranitelDBContext dBContext)
        {
            _dbContext = dBContext;
        }
        public IActionResult Navigate()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GroupStepOne(GroupStepOneViewModel model)
        {
            //ПРОВЕРКА ДАТЫ\\
            if (DateTime.Now.Date.Year - model.DateBirthday.Date.Year < 14)
            { ModelState.AddModelError(nameof(model.DateBirthday), "Возраст гостей - от 14 лет"); }

            else if (DateTime.Now.Date.Year - model.DateBirthday.Date.Year == 14)
            {
                if (DateTime.Now.Date.Month < model.DateBirthday.Date.Month)
                { ModelState.AddModelError(nameof(model.DateBirthday), "Возраст гостей - от 14 лет"); }

                else if (DateTime.Now.Date.Month == model.DateBirthday.Date.Month)
                {
                    if (DateTime.Now.Date.Day < model.DateBirthday.Date.Day)
                    { ModelState.AddModelError(nameof(model.DateBirthday), "Возраст гостей - от 14 лет"); }
                }
            }

            if (DateTime.Now.Date.Year - model.DateBirthday.Date.Year > 100)
            { ModelState.AddModelError(nameof(model.DateBirthday), "Вам не может быть более 100 лет"); }
            //ПРОВЕРКА ДАТЫ\\

            //ПРОВЕРКА НА ЧС\\
            if (ModelState.IsValid)
            {
                foreach (var csV in _dbContext.CherniySpisoks)
                {
                    if (model.PasSeries == csV.SeriaPas && model.PasNumber == csV.NomerPas)
                    {
                        ModelState.AddModelError(nameof(model.Error),
                        csV.Familia + " "
                        + csV.Imya + " "
                        + csV.Otchestvo + " Находится в черном списке");
                    }
                }
            }
            //ПРОВЕРКА НА ЧС\\

            if (ModelState.IsValid)
            {
                var visitor = new Posetiteli
                {
                    SeriaPas = model.PasSeries,
                    NomerPas = model.PasNumber,
                    Familia = model.FirstName,
                    Imya = model.Name,
                    Otchestvo = model.Patronomic,
                    NomerTelefona = model.PhoneNumber,
                    DataRozhdenia = model.DateBirthday
                };

                privacyViewModel.Visitors.Add(visitor);
            }

            return View(privacyViewModel);
        }

        public IActionResult GroupStepOne()
        {
            if(HttpContext.User.Identity.IsAuthenticated)
            { return View(privacyViewModel); }
            else
            {
                privacyViewModel.Visitors.Clear();

                return View(privacyViewModel);
            }
            
        }

        public async Task<IActionResult> GroupStepTwo()
        {
            PodrazdeleniaRepository podrazdeleniaRepository = new PodrazdeleniaRepository(_dbContext);
            CeliRepository celiRepository = new CeliRepository(_dbContext);

            regViewModel.Visitors = privacyViewModel.Visitors;
            regViewModel.Divisions = podrazdeleniaRepository.Get();
            regViewModel.Targets = celiRepository.Get();

            return View(regViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> GroupStepTwo(GroupStepTwoViewModel model)
        {


            //Проверка количества гостей\\
            if (ModelState.IsValid)
            {
                if (regViewModel.Visitors.Count < 5)
                { ModelState.AddModelError(nameof(model.CountError), "В груповой заявке должно быть минимум 5 гостей"); }
            }
            //Проверка количества гостей\\

            //Проверка даты\\ - "систематическая"
            if (model.DateRegistration < DateTime.Now)
            { ModelState.AddModelError(nameof(model.DateRegistration), "Выбранная дата - прошлое"); }
            //Проверка даты\\

            if (ModelState.IsValid)
            {
                var visitorRepository = new PosetiteliRepository(_dbContext);
                var appliRepository = new ZajavkiRepository(_dbContext);
                var usersRepository = new UsersRepository(_dbContext);

                if(HttpContext.User.Identity.IsAuthenticated)
                {
                    var curUser = await usersRepository.GetByLogin(HttpContext.User.Identity.Name);

                    await appliRepository.Add(curUser.IdPolzovatelia,
                        int.Parse(model.SelectDivision.Split(' ')[0]),
                        int.Parse(model.SelectTarget.Split(' ')[0]),
                        model.DateRegistration);
                }
                else
                {
                    await appliRepository.Add(7,
                        int.Parse(model.SelectDivision.Split(' ')[0]),
                        int.Parse(model.SelectTarget.Split(' ')[0]),
                        model.DateRegistration);
                }
                

                var appli = await appliRepository.GetLast();

                await visitorRepository.AddList(appli, regViewModel.Visitors);


            }

            return View(regViewModel);
        }

        public async Task<IActionResult> Solo()
        {
            SoloViewModel model = new SoloViewModel();
            PodrazdeleniaRepository podrazdeleniaRepository = new PodrazdeleniaRepository(_dbContext);
            CeliRepository celiRepository = new CeliRepository(_dbContext);

            soloViewModel.Divisions = podrazdeleniaRepository.Get();
            soloViewModel.Targets = celiRepository.Get();

            return View(soloViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Solo(SoloViewModel model)
        {
            //ПРОВЕРКА ДАТЫ\\
            if (DateTime.Now.Date.Year - model.DateBirthday.Date.Year < 14)
            { ModelState.AddModelError(nameof(model.DateBirthday), "Возраст гостей - от 14 лет"); }

            else if (DateTime.Now.Date.Year - model.DateBirthday.Date.Year == 14)
            {
                if (DateTime.Now.Date.Month < model.DateBirthday.Date.Month)
                { ModelState.AddModelError(nameof(model.DateBirthday), "Возраст гостей - от 14 лет"); }

                else if (DateTime.Now.Date.Month == model.DateBirthday.Date.Month)
                {
                    if (DateTime.Now.Date.Day < model.DateBirthday.Date.Day)
                    { ModelState.AddModelError(nameof(model.DateBirthday), "Возраст гостей - от 14 лет"); }
                }
            }

            if (DateTime.Now.Date.Year - model.DateBirthday.Date.Year > 100)
            { ModelState.AddModelError(nameof(model.DateBirthday), "Вам не может быть более 100 лет"); }

            if (model.DateRegistration < DateTime.Now)
            { ModelState.AddModelError(nameof(model.DateRegistration), "Выбранная дата - прошлое"); }
            //ПРОВЕРКА ДАТЫ\\

            //ПРОВЕРКА НА ЧС\\
            if (ModelState.IsValid)
            {
                if (_dbContext.CherniySpisoks.FirstOrDefault(v => v.SeriaPas == model.PasSeries && v.NomerPas == model.PasNumber) != null)
                {
                    ModelState.AddModelError(nameof(model.Error),
                        model.FirstName + " "
                        + model.Name + " "
                        + model.Patronomic + " находится в черном списке");
                }
            }
            //ПРОВЕРКА НА ЧС\\


            if(ModelState.IsValid)
            {
                var visitor = new Posetiteli
                {
                    SeriaPas = model.PasSeries,
                    NomerPas = model.PasNumber,
                    Familia = model.FirstName,
                    Imya = model.Name,
                    Otchestvo = model.Patronomic,
                    NomerTelefona = model.PhoneNumber,
                    DataRozhdenia = model.DateBirthday
                };
                model.Visitors.Add(visitor);


                var visitorRepository = new PosetiteliRepository(_dbContext);
                var appliRepository = new ZajavkiRepository(_dbContext);
                var usersRepository = new UsersRepository(_dbContext);

                if (HttpContext.User.Identity.IsAuthenticated)
                {
                    var curUser = await usersRepository.GetByLogin(HttpContext.User.Identity.Name);

                    await appliRepository.Add(curUser.IdPolzovatelia,
                        int.Parse(model.SelectDivision.Split(' ')[0]),
                        int.Parse(model.SelectTarget.Split(' ')[0]),
                        model.DateRegistration);
                }
                else
                {
                    await appliRepository.Add(7,
                        int.Parse(model.SelectDivision.Split(' ')[0]),
                        int.Parse(model.SelectTarget.Split(' ')[0]),
                        model.DateRegistration);
                }

                var appli = await appliRepository.GetLast();

                await visitorRepository.AddList(appli, model.Visitors);
            }

            return View(soloViewModel);
        }
    }
}

HranitelPROWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HranitelPROWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HranitelPROWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HranitelPRO</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RegApplication" asp-action="Navigate">Перейти к оформлению</a>
                        </li>
                    </ul>

                    <ul class="navbar-nav">
                        @if (@Context.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" title="Manage" asp-controller="User" asp-action="index">@Context.User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link btn btn-link text-dark" asp-controller="Auth" asp-action="LogOut">Выйти</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Auth" asp-action="Registration">Зарегистрироваться</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Auth" asp-action="Login">Войти</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - HranitelPROWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>